
ALTER TABLE public."CP_CODIGO_PENAL" ADD COLUMN IF NOT EXISTS rotulo text;
ALTER TABLE public."CP_CODIGO_PENAL" ADD COLUMN IF NOT EXISTS texto text NOT NULL DEFAULT '';
ALTER TABLE public."CP_CODIGO_PENAL" ADD COLUMN IF NOT EXISTS ordem_numero numeric NOT NULL DEFAULT 0;
