
-- =============================================
-- SECURE RLS: Remove overly permissive DELETE/INSERT on law tables
-- Keep SELECT public, restrict mutations to service_role
-- =============================================

-- Helper: Drop and recreate policies for law tables
-- We'll do the main ones that have public DELETE/INSERT

-- CF88
DROP POLICY IF EXISTS "Deleção CF88" ON "CF88_CONSTITUICAO_FEDERAL";
DROP POLICY IF EXISTS "Inserção CF88" ON "CF88_CONSTITUICAO_FEDERAL";
CREATE POLICY "service_insert_cf88" ON "CF88_CONSTITUICAO_FEDERAL" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cf88" ON "CF88_CONSTITUICAO_FEDERAL" FOR DELETE TO service_role USING (true);

-- CP
DROP POLICY IF EXISTS "Deleção CP" ON "CP_CODIGO_PENAL";
DROP POLICY IF EXISTS "Inserção CP" ON "CP_CODIGO_PENAL";
CREATE POLICY "service_insert_cp" ON "CP_CODIGO_PENAL" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cp" ON "CP_CODIGO_PENAL" FOR DELETE TO service_role USING (true);

-- CC
DROP POLICY IF EXISTS "Deleção CC" ON "CC_CODIGO_CIVIL";
DROP POLICY IF EXISTS "Inserção CC" ON "CC_CODIGO_CIVIL";
CREATE POLICY "service_insert_cc" ON "CC_CODIGO_CIVIL" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cc" ON "CC_CODIGO_CIVIL" FOR DELETE TO service_role USING (true);

-- CPC
DROP POLICY IF EXISTS "Deleção CPC" ON "CPC_CODIGO_PROCESSO_CIVIL";
DROP POLICY IF EXISTS "Inserção CPC" ON "CPC_CODIGO_PROCESSO_CIVIL";
CREATE POLICY "service_insert_cpc" ON "CPC_CODIGO_PROCESSO_CIVIL" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cpc" ON "CPC_CODIGO_PROCESSO_CIVIL" FOR DELETE TO service_role USING (true);

-- CPP
DROP POLICY IF EXISTS "Deleção CPP" ON "CPP_CODIGO_PROCESSO_PENAL";
DROP POLICY IF EXISTS "Inserção CPP" ON "CPP_CODIGO_PROCESSO_PENAL";
CREATE POLICY "service_insert_cpp" ON "CPP_CODIGO_PROCESSO_PENAL" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cpp" ON "CPP_CODIGO_PROCESSO_PENAL" FOR DELETE TO service_role USING (true);

-- CTN
DROP POLICY IF EXISTS "Deleção CTN" ON "CTN_CODIGO_TRIBUTARIO_NACIONAL";
DROP POLICY IF EXISTS "Inserção CTN" ON "CTN_CODIGO_TRIBUTARIO_NACIONAL";
CREATE POLICY "service_insert_ctn" ON "CTN_CODIGO_TRIBUTARIO_NACIONAL" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_ctn" ON "CTN_CODIGO_TRIBUTARIO_NACIONAL" FOR DELETE TO service_role USING (true);

-- CDC
DROP POLICY IF EXISTS "Deleção CDC" ON "CDC_CODIGO_DEFESA_CONSUMIDOR";
DROP POLICY IF EXISTS "Inserção CDC" ON "CDC_CODIGO_DEFESA_CONSUMIDOR";
CREATE POLICY "service_insert_cdc" ON "CDC_CODIGO_DEFESA_CONSUMIDOR" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cdc" ON "CDC_CODIGO_DEFESA_CONSUMIDOR" FOR DELETE TO service_role USING (true);

-- CLT
DROP POLICY IF EXISTS "Deleção CLT" ON "CLT_CONSOLIDACAO_LEIS_TRABALHO";
DROP POLICY IF EXISTS "Inserção CLT" ON "CLT_CONSOLIDACAO_LEIS_TRABALHO";
CREATE POLICY "service_insert_clt" ON "CLT_CONSOLIDACAO_LEIS_TRABALHO" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_clt" ON "CLT_CONSOLIDACAO_LEIS_TRABALHO" FOR DELETE TO service_role USING (true);

-- ECA
DROP POLICY IF EXISTS "Deleção ECA" ON "ECA_ESTATUTO_CRIANCA_ADOLESCENTE";
DROP POLICY IF EXISTS "Inserção ECA" ON "ECA_ESTATUTO_CRIANCA_ADOLESCENTE";
CREATE POLICY "service_insert_eca" ON "ECA_ESTATUTO_CRIANCA_ADOLESCENTE" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_eca" ON "ECA_ESTATUTO_CRIANCA_ADOLESCENTE" FOR DELETE TO service_role USING (true);

-- CTB
DROP POLICY IF EXISTS "Deleção CTB" ON "CTB_CODIGO_TRANSITO_BRASILEIRO";
DROP POLICY IF EXISTS "Inserção CTB" ON "CTB_CODIGO_TRANSITO_BRASILEIRO";
CREATE POLICY "service_insert_ctb" ON "CTB_CODIGO_TRANSITO_BRASILEIRO" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_ctb" ON "CTB_CODIGO_TRANSITO_BRASILEIRO" FOR DELETE TO service_role USING (true);

-- EI
DROP POLICY IF EXISTS "Deleção EI" ON "EI_ESTATUTO_IDOSO";
DROP POLICY IF EXISTS "Inserção EI" ON "EI_ESTATUTO_IDOSO";
CREATE POLICY "service_insert_ei" ON "EI_ESTATUTO_IDOSO" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_ei" ON "EI_ESTATUTO_IDOSO" FOR DELETE TO service_role USING (true);

-- EPD
DROP POLICY IF EXISTS "Deleção EPD" ON "EPD_ESTATUTO_PESSOA_DEFICIENCIA";
DROP POLICY IF EXISTS "Inserção EPD" ON "EPD_ESTATUTO_PESSOA_DEFICIENCIA";
CREATE POLICY "service_insert_epd" ON "EPD_ESTATUTO_PESSOA_DEFICIENCIA" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_epd" ON "EPD_ESTATUTO_PESSOA_DEFICIENCIA" FOR DELETE TO service_role USING (true);

-- Secure anotacoes_artigo: only owner can read/modify their annotations
DROP POLICY IF EXISTS "Anyone can delete anotacoes" ON anotacoes_artigo;
DROP POLICY IF EXISTS "Anyone can insert anotacoes" ON anotacoes_artigo;
DROP POLICY IF EXISTS "Anyone can read anotacoes" ON anotacoes_artigo;
DROP POLICY IF EXISTS "Anyone can update anotacoes" ON anotacoes_artigo;

-- Public read for suggested annotations, user-specific for personal ones
CREATE POLICY "read_own_or_suggested_anotacoes" ON anotacoes_artigo
  FOR SELECT TO anon, authenticated
  USING (sugerida = true OR user_id = auth.uid());

CREATE POLICY "insert_own_anotacoes" ON anotacoes_artigo
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "update_own_anotacoes" ON anotacoes_artigo
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "delete_own_anotacoes" ON anotacoes_artigo
  FOR DELETE TO authenticated
  USING (user_id = auth.uid());

-- Also secure remaining law tables
DROP POLICY IF EXISTS "Deleção CAGUA" ON "CAGUA_CODIGO_AGUAS";
DROP POLICY IF EXISTS "Inserção CAGUA" ON "CAGUA_CODIGO_AGUAS";
CREATE POLICY "service_insert_cagua" ON "CAGUA_CODIGO_AGUAS" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cagua" ON "CAGUA_CODIGO_AGUAS" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção CBA" ON "CBA_CODIGO_BRASILEIRO_AERONAUTICA";
DROP POLICY IF EXISTS "Inserção CBA" ON "CBA_CODIGO_BRASILEIRO_AERONAUTICA";
CREATE POLICY "service_insert_cba" ON "CBA_CODIGO_BRASILEIRO_AERONAUTICA" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cba" ON "CBA_CODIGO_BRASILEIRO_AERONAUTICA" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção CCOM" ON "CCOM_CODIGO_COMERCIAL";
DROP POLICY IF EXISTS "Inserção CCOM" ON "CCOM_CODIGO_COMERCIAL";
CREATE POLICY "service_insert_ccom" ON "CCOM_CODIGO_COMERCIAL" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_ccom" ON "CCOM_CODIGO_COMERCIAL" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção CE" ON "CE_CODIGO_ELEITORAL";
DROP POLICY IF EXISTS "Inserção CE" ON "CE_CODIGO_ELEITORAL";
CREATE POLICY "service_insert_ce" ON "CE_CODIGO_ELEITORAL" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_ce" ON "CE_CODIGO_ELEITORAL" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção CFLOR" ON "CFLOR_CODIGO_FLORESTAL";
DROP POLICY IF EXISTS "Inserção CFLOR" ON "CFLOR_CODIGO_FLORESTAL";
CREATE POLICY "service_insert_cflor" ON "CFLOR_CODIGO_FLORESTAL" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cflor" ON "CFLOR_CODIGO_FLORESTAL" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção CMIN" ON "CMIN_CODIGO_MINAS";
DROP POLICY IF EXISTS "Inserção CMIN" ON "CMIN_CODIGO_MINAS";
CREATE POLICY "service_insert_cmin" ON "CMIN_CODIGO_MINAS" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cmin" ON "CMIN_CODIGO_MINAS" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção CTEL" ON "CTEL_CODIGO_TELECOMUNICACOES";
DROP POLICY IF EXISTS "Inserção CTEL" ON "CTEL_CODIGO_TELECOMUNICACOES";
CREATE POLICY "service_insert_ctel" ON "CTEL_CODIGO_TELECOMUNICACOES" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_ctel" ON "CTEL_CODIGO_TELECOMUNICACOES" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção CPM" ON "CPM_CODIGO_PENAL_MILITAR";
DROP POLICY IF EXISTS "Inserção CPM" ON "CPM_CODIGO_PENAL_MILITAR";
CREATE POLICY "service_insert_cpm" ON "CPM_CODIGO_PENAL_MILITAR" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cpm" ON "CPM_CODIGO_PENAL_MILITAR" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção CPPM" ON "CPPM_CODIGO_PROCESSO_PENAL_MILITAR";
DROP POLICY IF EXISTS "Inserção CPPM" ON "CPPM_CODIGO_PROCESSO_PENAL_MILITAR";
CREATE POLICY "service_insert_cppm" ON "CPPM_CODIGO_PROCESSO_PENAL_MILITAR" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_cppm" ON "CPPM_CODIGO_PROCESSO_PENAL_MILITAR" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EC" ON "EC_ESTATUTO_CIDADE";
DROP POLICY IF EXISTS "Inserção EC" ON "EC_ESTATUTO_CIDADE";
CREATE POLICY "service_insert_ec" ON "EC_ESTATUTO_CIDADE" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_ec" ON "EC_ESTATUTO_CIDADE" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção ED" ON "ED_ESTATUTO_DESARMAMENTO";
DROP POLICY IF EXISTS "Inserção ED" ON "ED_ESTATUTO_DESARMAMENTO";
CREATE POLICY "service_insert_ed" ON "ED_ESTATUTO_DESARMAMENTO" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_ed" ON "ED_ESTATUTO_DESARMAMENTO" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EIND" ON "EIND_ESTATUTO_INDIO";
DROP POLICY IF EXISTS "Inserção EIND" ON "EIND_ESTATUTO_INDIO";
CREATE POLICY "service_insert_eind" ON "EIND_ESTATUTO_INDIO" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_eind" ON "EIND_ESTATUTO_INDIO" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EIR" ON "EIR_ESTATUTO_IGUALDADE_RACIAL";
DROP POLICY IF EXISTS "Inserção EIR" ON "EIR_ESTATUTO_IGUALDADE_RACIAL";
CREATE POLICY "service_insert_eir" ON "EIR_ESTATUTO_IGUALDADE_RACIAL" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_eir" ON "EIR_ESTATUTO_IGUALDADE_RACIAL" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EJ" ON "EJ_ESTATUTO_JUVENTUDE";
DROP POLICY IF EXISTS "Inserção EJ" ON "EJ_ESTATUTO_JUVENTUDE";
CREATE POLICY "service_insert_ej" ON "EJ_ESTATUTO_JUVENTUDE" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_ej" ON "EJ_ESTATUTO_JUVENTUDE" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EM" ON "EM_ESTATUTO_MILITARES";
DROP POLICY IF EXISTS "Inserção EM" ON "EM_ESTATUTO_MILITARES";
CREATE POLICY "service_insert_em" ON "EM_ESTATUTO_MILITARES" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_em" ON "EM_ESTATUTO_MILITARES" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EME" ON "EME_ESTATUTO_MICROEMPRESA";
DROP POLICY IF EXISTS "Inserção EME" ON "EME_ESTATUTO_MICROEMPRESA";
CREATE POLICY "service_insert_eme" ON "EME_ESTATUTO_MICROEMPRESA" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_eme" ON "EME_ESTATUTO_MICROEMPRESA" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EMET" ON "EMET_ESTATUTO_METROPOLE";
DROP POLICY IF EXISTS "Inserção EMET" ON "EMET_ESTATUTO_METROPOLE";
CREATE POLICY "service_insert_emet" ON "EMET_ESTATUTO_METROPOLE" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_emet" ON "EMET_ESTATUTO_METROPOLE" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EMIG" ON "EMIG_ESTATUTO_MIGRACAO";
DROP POLICY IF EXISTS "Inserção EMIG" ON "EMIG_ESTATUTO_MIGRACAO";
CREATE POLICY "service_insert_emig" ON "EMIG_ESTATUTO_MIGRACAO" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_emig" ON "EMIG_ESTATUTO_MIGRACAO" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EMUS" ON "EMUS_ESTATUTO_MUSEUS";
DROP POLICY IF EXISTS "Inserção EMUS" ON "EMUS_ESTATUTO_MUSEUS";
CREATE POLICY "service_insert_emus" ON "EMUS_ESTATUTO_MUSEUS" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_emus" ON "EMUS_ESTATUTO_MUSEUS" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EOAB" ON "EOAB_ESTATUTO_OAB";
DROP POLICY IF EXISTS "Inserção EOAB" ON "EOAB_ESTATUTO_OAB";
CREATE POLICY "service_insert_eoab" ON "EOAB_ESTATUTO_OAB" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_eoab" ON "EOAB_ESTATUTO_OAB" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EPC" ON "EPC_ESTATUTO_PESSOA_CANCER";
DROP POLICY IF EXISTS "Inserção EPC" ON "EPC_ESTATUTO_PESSOA_CANCER";
CREATE POLICY "service_insert_epc" ON "EPC_ESTATUTO_PESSOA_CANCER" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_epc" ON "EPC_ESTATUTO_PESSOA_CANCER" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção EREF" ON "EREF_ESTATUTO_REFUGIADO";
DROP POLICY IF EXISTS "Inserção EREF" ON "EREF_ESTATUTO_REFUGIADO";
CREATE POLICY "service_insert_eref" ON "EREF_ESTATUTO_REFUGIADO" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_eref" ON "EREF_ESTATUTO_REFUGIADO" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção ET" ON "ET_ESTATUTO_TORCEDOR";
DROP POLICY IF EXISTS "Inserção ET" ON "ET_ESTATUTO_TORCEDOR";
CREATE POLICY "service_insert_et" ON "ET_ESTATUTO_TORCEDOR" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_et" ON "ET_ESTATUTO_TORCEDOR" FOR DELETE TO service_role USING (true);

DROP POLICY IF EXISTS "Deleção ETERRA" ON "ETERRA_ESTATUTO_TERRA";
DROP POLICY IF EXISTS "Inserção ETERRA" ON "ETERRA_ESTATUTO_TERRA";
CREATE POLICY "service_insert_eterra" ON "ETERRA_ESTATUTO_TERRA" FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "service_delete_eterra" ON "ETERRA_ESTATUTO_TERRA" FOR DELETE TO service_role USING (true);

-- Enable realtime on anotacoes_artigo for cross-device sync
ALTER PUBLICATION supabase_realtime ADD TABLE anotacoes_artigo;
